/* C code for program StriplineHER, generated by snc from ../StriplineHER.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../StriplineHER.stt"
#include <stdio.h>
# line 4 "../StriplineHER.stt"
#include <stdlib.h>
# line 5 "../StriplineHER.stt"
#include <assert.h>
# line 6 "../StriplineHER.stt"
#include <time.h>
# line 7 "../StriplineHER.stt"
#include <math.h>
# line 8 "../StriplineHER.stt"
#include <unistd.h>
# line 9 "../StriplineHER.stt"
#include "MT.h"
# line 24 "../StriplineHER.stt"

  double x0;
  double x1;
  double y;

  double Uniform(void)
  {
    return genrand_real3();
  }

  double rand_Lnormal(double mu, double sigma)
  {
    double y = mu + sigma*sqrt(-2.0*log(Uniform()))*sin(2.0*M_PI*Uniform()); //gauss random number
    return y;
  }


/* Variable declarations */
# line 11 "../StriplineHER.stt"
static	double X0;
# line 11 "../StriplineHER.stt"
static	double X1;
# line 11 "../StriplineHER.stt"
static	double Y0;
# line 11 "../StriplineHER.stt"
static	double C0;
# line 11 "../StriplineHER.stt"
static	double G0;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "her_efficiency" ******/

/* Event function for state "init" in state set "her_efficiency" */
static seqBool seqg_event_her_efficiency_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "her_efficiency" */
static void seqg_action_her_efficiency_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 47 "../StriplineHER.stt"
			seq_pvGetTmo(seqg_env, 0/*X0*/, DEFAULT, DEFAULT_TIMEOUT);
# line 48 "../StriplineHER.stt"
			seq_pvGetTmo(seqg_env, 1/*X1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 50 "../StriplineHER.stt"
			printf("her_efficiency initialization done.\n");
			
        init_genrand((unsigned)time(NULL));
      
		}
		return;
	}
}

/****** Code for state "efficiency" in state set "her_efficiency" ******/

/* Event function for state "efficiency" in state set "her_efficiency" */
static seqBool seqg_event_her_efficiency_0_efficiency(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "efficiency" in state set "her_efficiency" */
static void seqg_action_her_efficiency_0_efficiency(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 63 "../StriplineHER.stt"
			x0 = X0;
# line 64 "../StriplineHER.stt"
			x1 = X1;
			
	y = pow(X1 - 5.1/(4.*pow(M_PI,2.)) * pow(X0,2.) + 5./M_PI * X0 - 6., 2.) + 10 * (1. - 1./(8.*M_PI)) * cos(X0) + 10. 
  + rand_Lnormal(0., 1.e-3);
      
# line 71 "../StriplineHER.stt"
			Y0 = 200 - y;
# line 72 "../StriplineHER.stt"
			seq_pvPutTmo(seqg_env, 2/*Y0*/, DEFAULT, DEFAULT_TIMEOUT);
			
	usleep(100000);
      
		}
		return;
	}
}

/****** Code for state "init" in state set "her_lm" ******/

/* Event function for state "init" in state set "her_lm" */
static seqBool seqg_event_her_lm_1_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "her_lm" */
static void seqg_action_her_lm_1_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 88 "../StriplineHER.stt"
			printf("her_lm initialization done.\n");
		}
		return;
	}
}

/****** Code for state "lm" in state set "her_lm" ******/

/* Event function for state "lm" in state set "her_lm" */
static seqBool seqg_event_her_lm_1_lm(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "lm" in state set "her_lm" */
static void seqg_action_her_lm_1_lm(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 97 "../StriplineHER.stt"
			G0 = rand_Lnormal(1.e-1, 3.e-2);
# line 98 "../StriplineHER.stt"
			if (G0 < 8.e-2)
			{
# line 100 "../StriplineHER.stt"
				C0 = 0.;
# line 101 "../StriplineHER.stt"
				G0 = 0.;
			}
			else
			{
# line 105 "../StriplineHER.stt"
				C0 = 1. - exp(-pow(x0 - M_PI, 2.) / 10. - pow(x1 - 2.275, 2.) / 10.) + rand_Lnormal(1.e-2, 1.e-2);
# line 106 "../StriplineHER.stt"
				G0 = 1.;
			}
# line 109 "../StriplineHER.stt"
			seq_pvPutTmo(seqg_env, 3/*C0*/, DEFAULT, DEFAULT_TIMEOUT);
# line 110 "../StriplineHER.stt"
			seq_pvPutTmo(seqg_env, 4/*G0*/, DEFAULT, DEFAULT_TIMEOUT);
			
	usleep(500000);
      
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"TEST:X0", (size_t)&X0, "X0", P_DOUBLE, 1, 1, 0, 1, 0, 0},
	{"TEST:X1", (size_t)&X1, "X1", P_DOUBLE, 1, 2, 0, 1, 0, 0},
	{"TEST:Y0", (size_t)&Y0, "Y0", P_DOUBLE, 1, 3, 0, 0, 0, 0},
	{"TEST:C0", (size_t)&C0, "C0", P_DOUBLE, 1, 4, 0, 1, 0, 0},
	{"TEST:G0", (size_t)&G0, "G0", P_DOUBLE, 1, 5, 0, 1, 0, 0},
};

/* Event masks for state set "her_efficiency" */
static const seqMask seqg_mask_her_efficiency_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_her_efficiency_0_efficiency[] = {
	0x00000000,
};

/* State table for state set "her_efficiency" */
static seqState seqg_states_her_efficiency[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_her_efficiency_0_init,
	/* event function */    seqg_event_her_efficiency_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_her_efficiency_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "efficiency",
	/* action function */   seqg_action_her_efficiency_0_efficiency,
	/* event function */    seqg_event_her_efficiency_0_efficiency,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_her_efficiency_0_efficiency,
	/* state options */     (0)
	},
};

/* Event masks for state set "her_lm" */
static const seqMask seqg_mask_her_lm_1_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_her_lm_1_lm[] = {
	0x00000000,
};

/* State table for state set "her_lm" */
static seqState seqg_states_her_lm[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_her_lm_1_init,
	/* event function */    seqg_event_her_lm_1_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_her_lm_1_init,
	/* state options */     (0)
	},
	{
	/* state name */        "lm",
	/* action function */   seqg_action_her_lm_1_lm,
	/* event function */    seqg_event_her_lm_1_lm,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_her_lm_1_lm,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "her_efficiency",
	/* states */            seqg_states_her_efficiency,
	/* number of states */  2
	},

	{
	/* state set name */    "her_lm",
	/* states */            seqg_states_her_lm,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram StriplineHER = {
	/* magic number */      2002008,
	/* program name */      "StriplineHER",
	/* channels */          seqg_chans,
	/* num. channels */     5,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void StriplineHERRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&StriplineHER);
}
epicsExportRegistrar(StriplineHERRegistrar);
