/* C code for program StriplineHER, generated by snc from ../StriplineHER.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../StriplineHER.stt"
#include <stdio.h>
# line 4 "../StriplineHER.stt"
#include <stdlib.h>
# line 5 "../StriplineHER.stt"
#include <assert.h>
# line 6 "../StriplineHER.stt"
#include <time.h>
# line 7 "../StriplineHER.stt"
#include <math.h>
# line 8 "../StriplineHER.stt"
#include <unistd.h>
# line 9 "../StriplineHER.stt"
#include "MT.h"
# line 28 "../StriplineHER.stt"

  double x0;
  double x1;
  double y;
  double lm1;
  //double lm2;
  //double lm3;
  //double th;

  double Uniform(void)
  {
    return genrand_real3();
  }

  double rand_Lnormal(double mu, double sigma)
  {
    double y= mu + sigma*sqrt(-2.0*log(Uniform()))*sin(2.0*M_PI*Uniform());//gauss random number
    return y;
  }


/* Variable declarations */
# line 11 "../StriplineHER.stt"
static	double X0;
# line 11 "../StriplineHER.stt"
static	double X1;
# line 11 "../StriplineHER.stt"
static	double LM0;
# line 11 "../StriplineHER.stt"
static	double Y;
# line 11 "../StriplineHER.stt"
static	double LM2;
# line 11 "../StriplineHER.stt"
static	double LM3;
# line 11 "../StriplineHER.stt"
static	double TH;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "her_stripline" ******/

/* Event function for state "init" in state set "her_stripline" */
static seqBool seqg_event_her_stripline_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "her_stripline" */
static void seqg_action_her_stripline_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 55 "../StriplineHER.stt"
			seq_pvGetTmo(seqg_env, 0/*X0*/, DEFAULT, DEFAULT_TIMEOUT);
# line 56 "../StriplineHER.stt"
			seq_pvGetTmo(seqg_env, 1/*X1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 62 "../StriplineHER.stt"
			printf("StriplineHER initialization done.\n");
			
        init_genrand((unsigned)time(NULL));
      
		}
		return;
	}
}

/****** Code for state "fit" in state set "her_stripline" ******/

/* Event function for state "fit" in state set "her_stripline" */
static seqBool seqg_event_her_stripline_0_fit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "fit" in state set "her_stripline" */
static void seqg_action_her_stripline_0_fit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 75 "../StriplineHER.stt"
			x0 = X0;
# line 76 "../StriplineHER.stt"
			x1 = X1;
			
	y = pow(X1 - 5.1/(4.*pow(M_PI,2.)) * pow(X0,2.) + 5./M_PI * X0 - 6., 2.) + 10 * (1. - 1./(8.*M_PI)) * cos(X0) + 10. 
  + rand_Lnormal(0., 1.e-3);
	
      
# line 88 "../StriplineHER.stt"
			Y = y;
# line 90 "../StriplineHER.stt"
			seq_pvPutTmo(seqg_env, 2/*Y*/, DEFAULT, DEFAULT_TIMEOUT);
			
        usleep(0.1e+6);
      
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"TEST:X0", (size_t)&X0, "X0", P_DOUBLE, 1, 1, 0, 1, 0, 0},
	{"TEST:X1", (size_t)&X1, "X1", P_DOUBLE, 1, 2, 0, 1, 0, 0},
	{"TEST:Y", (size_t)&Y, "Y", P_DOUBLE, 1, 3, 0, 0, 0, 0},
	{"TEST:LM0", (size_t)&LM0, "LM0", P_DOUBLE, 1, 4, 0, 0, 0, 0},
};

/* Event masks for state set "her_stripline" */
static const seqMask seqg_mask_her_stripline_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_her_stripline_0_fit[] = {
	0x00000000,
};

/* State table for state set "her_stripline" */
static seqState seqg_states_her_stripline[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_her_stripline_0_init,
	/* event function */    seqg_event_her_stripline_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_her_stripline_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "fit",
	/* action function */   seqg_action_her_stripline_0_fit,
	/* event function */    seqg_event_her_stripline_0_fit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_her_stripline_0_fit,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "her_stripline",
	/* states */            seqg_states_her_stripline,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram StriplineHER = {
	/* magic number */      2002008,
	/* program name */      "StriplineHER",
	/* channels */          seqg_chans,
	/* num. channels */     4,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void StriplineHERRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&StriplineHER);
}
epicsExportRegistrar(StriplineHERRegistrar);
