/* C code for program StriplineLER, generated by snc from ../StriplineLER.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../StriplineLER.stt"
#include <stdio.h>
# line 4 "../StriplineLER.stt"
#include <stdlib.h>
# line 5 "../StriplineLER.stt"
#include <assert.h>
# line 6 "../StriplineLER.stt"
#include <time.h>
# line 7 "../StriplineLER.stt"
#include "fitfunc.h"
# line 28 "../StriplineLER.stt"

  void *obj;
  double v1meas;
  double v2meas;
  double v3meas;
  double v4meas;
  double posx;
  double posy;


/* Variable declarations */
# line 9 "../StriplineLER.stt"
static	double MEASV1;
# line 9 "../StriplineLER.stt"
static	double MEASV2;
# line 9 "../StriplineLER.stt"
static	double MEASV3;
# line 9 "../StriplineLER.stt"
static	double MEASV4;
# line 20 "../StriplineLER.stt"
static	double MEASV1_OLD;
# line 20 "../StriplineLER.stt"
static	double MEASV2_OLD;
# line 20 "../StriplineLER.stt"
static	double MEASV3_OLD;
# line 20 "../StriplineLER.stt"
static	double MEASV4_OLD;
# line 21 "../StriplineLER.stt"
static	double SUMMEASV;
# line 24 "../StriplineLER.stt"
static	double POSX;
# line 24 "../StriplineLER.stt"
static	double POSY;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "ler_stripline" ******/

/* Event function for state "init" in state set "ler_stripline" */
static seqBool seqg_event_ler_stripline_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "ler_stripline" */
static void seqg_action_ler_stripline_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			/* C code definitions */
# line 44 "../StriplineLER.stt"
			
        /* Create object and initialize */
        obj = new_object();
        call_init(obj, "bemmap_ler.dat");
      
# line 50 "../StriplineLER.stt"
			seq_pvGetTmo(seqg_env, 0/*MEASV1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 51 "../StriplineLER.stt"
			seq_pvGetTmo(seqg_env, 1/*MEASV2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 52 "../StriplineLER.stt"
			seq_pvGetTmo(seqg_env, 2/*MEASV3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 53 "../StriplineLER.stt"
			seq_pvGetTmo(seqg_env, 3/*MEASV4*/, DEFAULT, DEFAULT_TIMEOUT);
# line 55 "../StriplineLER.stt"
			MEASV1_OLD = MEASV1;
# line 56 "../StriplineLER.stt"
			MEASV2_OLD = MEASV2;
# line 57 "../StriplineLER.stt"
			MEASV3_OLD = MEASV3;
# line 58 "../StriplineLER.stt"
			MEASV4_OLD = MEASV4;
# line 60 "../StriplineLER.stt"
			printf("StriplineLER initialization done.\n");
		}
		return;
	}
}

/****** Code for state "fit" in state set "ler_stripline" ******/

/* Event function for state "fit" in state set "ler_stripline" */
static seqBool seqg_event_ler_stripline_0_fit(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 69 "../StriplineLER.stt"
	if ((MEASV1 != MEASV1_OLD) || (MEASV2 != MEASV2_OLD) || (MEASV3 != MEASV3_OLD) || (MEASV4 != MEASV4_OLD))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "fit" in state set "ler_stripline" */
static void seqg_action_ler_stripline_0_fit(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 74 "../StriplineLER.stt"
			SUMMEASV = MEASV1 + MEASV2 + MEASV3 + MEASV4;
# line 75 "../StriplineLER.stt"
			v1meas = MEASV1;
# line 76 "../StriplineLER.stt"
			v2meas = MEASV2;
# line 77 "../StriplineLER.stt"
			v3meas = MEASV3;
# line 78 "../StriplineLER.stt"
			v4meas = MEASV4;
			
        call_fit(obj, &v1meas, &v2meas, &v3meas, &v4meas, &posx, &posy);
      
# line 85 "../StriplineLER.stt"
			MEASV1_OLD = MEASV1;
# line 86 "../StriplineLER.stt"
			MEASV2_OLD = MEASV2;
# line 87 "../StriplineLER.stt"
			MEASV3_OLD = MEASV3;
# line 88 "../StriplineLER.stt"
			MEASV4_OLD = MEASV4;
# line 91 "../StriplineLER.stt"
			POSX = -posx;
# line 92 "../StriplineLER.stt"
			POSY = posy;
# line 93 "../StriplineLER.stt"
			seq_pvPutTmo(seqg_env, 5/*POSX*/, DEFAULT, DEFAULT_TIMEOUT);
# line 94 "../StriplineLER.stt"
			seq_pvPutTmo(seqg_env, 6/*POSY*/, DEFAULT, DEFAULT_TIMEOUT);
# line 95 "../StriplineLER.stt"
			seq_pvPutTmo(seqg_env, 4/*SUMMEASV*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"BMLD07:signals:sp.va", (size_t)&MEASV1, "MEASV1", P_DOUBLE, 1, 1, 0, 1, 0, 0},
	{"BMLD07:signals:sp.vb", (size_t)&MEASV2, "MEASV2", P_DOUBLE, 1, 2, 0, 1, 0, 0},
	{"BMLD07:signals:sp.vc", (size_t)&MEASV3, "MEASV3", P_DOUBLE, 1, 3, 0, 1, 0, 0},
	{"BMLD07:signals:sp.vd", (size_t)&MEASV4, "MEASV4", P_DOUBLE, 1, 4, 0, 1, 0, 0},
	{"BMLD07:INJ:Q", (size_t)&SUMMEASV, "SUMMEASV", P_DOUBLE, 1, 5, 0, 0, 0, 0},
	{"BMLD07:INJ:X", (size_t)&POSX, "POSX", P_DOUBLE, 1, 6, 0, 0, 0, 0},
	{"BMLD07:INJ:Y", (size_t)&POSY, "POSY", P_DOUBLE, 1, 7, 0, 0, 0, 0},
};

/* Event masks for state set "ler_stripline" */
static const seqMask seqg_mask_ler_stripline_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_ler_stripline_0_fit[] = {
	0x0000001e,
};

/* State table for state set "ler_stripline" */
static seqState seqg_states_ler_stripline[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_ler_stripline_0_init,
	/* event function */    seqg_event_ler_stripline_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ler_stripline_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "fit",
	/* action function */   seqg_action_ler_stripline_0_fit,
	/* event function */    seqg_event_ler_stripline_0_fit,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ler_stripline_0_fit,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ler_stripline",
	/* states */            seqg_states_ler_stripline,
	/* number of states */  2
	},
};

/* Program table (global) */
seqProgram StriplineLER = {
	/* magic number */      2002008,
	/* program name */      "StriplineLER",
	/* channels */          seqg_chans,
	/* num. channels */     7,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void StriplineLERRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&StriplineLER);
}
epicsExportRegistrar(StriplineLERRegistrar);
